#index:
#    path: /
#    controller: App\Controller\DefaultController::index
ajax_comment:
  path: /account/
  defaults: { _controller: 'App\Controller\UserController::account' }
  requirements:
    _method: POST
